-- 数据服务薄编排：绑定投影 + Key 元数据（SQL 正文在 SQLREST，不进本表）

CREATE TABLE IF NOT EXISTS `dataapi_api_binding` (
  `id`                 varchar(20)   NOT NULL COMMENT '主键',
  `revision`           int           NOT NULL DEFAULT 1 COMMENT '乐观锁版本',
  `status`             varchar(32)   NOT NULL DEFAULT 'active' COMMENT '记录态 active/archived',
  `ws`                 varchar(64)   DEFAULT 'default' COMMENT '工作空间',
  `remark`             varchar(512)  DEFAULT NULL COMMENT '备注',
  `name`               varchar(256)  NOT NULL COMMENT 'API 展示名',
  `public_path`        varchar(512)  NOT NULL COMMENT '对外路径，如 /api/gmv/daily',
  `method`             varchar(16)   NOT NULL DEFAULT 'GET' COMMENT 'HTTP 方法',
  `sqlrest_api_id`     varchar(64)   DEFAULT NULL COMMENT 'SQLREST assignment id',
  `sqlrest_commit_id`  varchar(64)   DEFAULT NULL COMMENT '当前上线 commitId',
  `sqlrest_version`    int           DEFAULT NULL COMMENT '当前上线 version',
  `source_kind`        varchar(32)   NOT NULL DEFAULT 'sql' COMMENT 'asset/metric/sql',
  `source_ref`         varchar(512)  DEFAULT NULL COMMENT '资产键/指标ID/说明',
  `state`              varchar(32)   NOT NULL DEFAULT 'draft' COMMENT 'draft/published/retired',
  `apisix_route_id`    varchar(128)  DEFAULT NULL COMMENT 'APISIX 路由 id',
  `auth_mode`          varchar(32)   DEFAULT 'Token' COMMENT 'Token/OAuth2/None',
  `qps_limit`          int           DEFAULT 100 COMMENT '全局限流 QPS',
  `burst_limit`        int           DEFAULT 200 COMMENT 'Burst',
  `domain_code`        varchar(64)   DEFAULT NULL COMMENT '业务域',
  `owner_user`         varchar(64)   DEFAULT NULL COMMENT '负责人 user_id 或展示名',
  `publish_env`        varchar(32)   DEFAULT 'stg' COMMENT 'stg/prod',
  `content_type`       varchar(128)  DEFAULT 'application/x-www-form-urlencoded' COMMENT 'SQLREST contentType',
  `param_json`         text          DEFAULT NULL COMMENT '入参元数据 JSON（非 SQL）',
  `response_json`      text          DEFAULT NULL COMMENT '出参/封装元数据 JSON（非 SQL）',
  `last_publish_at`    datetime      DEFAULT NULL COMMENT '最近发布时间',
  `last_error`         varchar(512)  DEFAULT NULL COMMENT '最近同步错误',
  `delete_flag`        varchar(32)   DEFAULT 'NOT_DELETE' COMMENT '删除标志',
  `create_time`        datetime      DEFAULT NULL COMMENT '创建时间',
  `create_user`        varchar(20)   DEFAULT NULL COMMENT '创建用户',
  `update_time`        datetime      DEFAULT NULL COMMENT '修改时间',
  `update_user`        varchar(20)   DEFAULT NULL COMMENT '修改用户',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uq_dataapi_path` (`ws`,`public_path`,`method`) USING BTREE,
  KEY `idx_dataapi_state` (`state`) USING BTREE,
  KEY `idx_dataapi_sqlrest` (`sqlrest_api_id`) USING BTREE,
  KEY `idx_dataapi_domain` (`domain_code`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='数据服务：API 绑定投影';

CREATE TABLE IF NOT EXISTS `dataapi_api_key_meta` (
  `id`             varchar(20)   NOT NULL COMMENT '主键',
  `revision`       int           NOT NULL DEFAULT 1 COMMENT '乐观锁版本',
  `status`         varchar(32)   NOT NULL DEFAULT 'active' COMMENT 'active/revoked/pending',
  `ws`             varchar(64)   DEFAULT 'default' COMMENT '工作空间',
  `remark`         varchar(512)  DEFAULT NULL COMMENT '备注',
  `binding_id`     varchar(20)   NOT NULL COMMENT 'dataapi_api_binding.id',
  `consumer_name`  varchar(128)  NOT NULL COMMENT '订阅应用名',
  `applicant`      varchar(64)   DEFAULT NULL COMMENT '申请人',
  `key_hint`       varchar(32)   DEFAULT NULL COMMENT 'Key 末几位提示',
  `vault_path`     varchar(256)  DEFAULT NULL COMMENT 'Vault 路径',
  `ticket_id`      varchar(20)   DEFAULT NULL COMMENT '申请单 id',
  `expire_at`      datetime      DEFAULT NULL COMMENT '过期时间',
  `delete_flag`    varchar(32)   DEFAULT 'NOT_DELETE' COMMENT '删除标志',
  `create_time`    datetime      DEFAULT NULL COMMENT '创建时间',
  `create_user`    varchar(20)   DEFAULT NULL COMMENT '创建用户',
  `update_time`    datetime      DEFAULT NULL COMMENT '修改时间',
  `update_user`    varchar(20)   DEFAULT NULL COMMENT '修改用户',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_dataapi_key_binding` (`binding_id`) USING BTREE,
  KEY `idx_dataapi_key_status` (`status`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='数据服务：API Key 元数据';
